// log in as Troels
POST https://localhost:7198/auth/login
Content-Type: application/json

{ "Username" : "luskk", "Password" : "0605" }

###

GET https://localhost:7198/test/authorized
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKV1RTZXJ2aWNlQWNjZXNzVG9rZW4iLCJqdGkiOiJhYTMxZmNmMS04MjE4LTQwMDQtYjhlMC1jNWY3NGJiOWM2ZTYiLCJpYXQiOiIyOC8wMy8yMDIzIDE1LjQ0LjMwIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6Imx1c2trIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiU3R1ZGVudCIsIkRpc3BsYXlOYW1lIjoiTHVrYXN6IFNyYW1rb3dza2kiLCJFbWFpbCI6Imx1c2trQHZpYS5kayIsIkFnZSI6IjIzIiwiRG9tYWluIjoidmlhIiwiU2VjdXJpdHlMZXZlbCI6IjIiLCJleHAiOjE2ODAwMjE4NzAsImlzcyI6IkpXVEF1dGhlbnRpY2F0aW9uU2VydmVyIiwiYXVkIjoiSldUU2VydmljZUJsYXpvcldhc21DbGllbnQifQ.FmlhQBtQESfjl11sizdG42CJBRZ2fBeYXV5lyKg8d2H8f0dA6EcQVwih-ONJfHUNOGf5cR-P41yVZ22qDGNeMQ
